
version: "3.8"

services:
  # Our db service
  db:
    container_name: postgres
    image: postgres:14.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ../pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  # Our api service
  api:
    container_name: api
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    command: npm run start
    volumes:
      - ./backend:/twzbja/src/app
      - /twzbja/src/app/node_modules
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      - API_PORT=${API_PORT}
      - API_HOST=${API_HOST}
      - POSTGRES_CONNECTION=${POSTGRES_CONNECTION}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=db
      - RABBITMQ_URL=amqp://admin:123456@rabbitmq:5672
    depends_on:
      - db
      - rabbitmq

  # Our client service
  web:
    container_name: web
    build: 
      context: ./web
      dockerfile: Dockerfile
    restart: always
    command: npm run start
    volumes:
      - ./web:/twzbja/web/src/app
      - /twzbja/web/src/app/node_modules
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    depends_on:
      - api

  # Our nginx service
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html/index.html:/var/www/html/index.html
    ports:
      - 80:80
    depends_on:
      - web
      - api
  
  # RabbitMQ
  rabbitmq:
    container_name: rabbitmq2
    hostname: rabbitmq
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
  
  # Quarkus
  quarkus:
    container_name: quarkus
    build:
      context: ./quarkus-message-dispacher
      dockerfile: src/main/docker/Dockerfile.jvm
    restart: always
    command: java -jar /deployments/quarkus-run.jar
    ports:
      - 8082:8082
    depends_on:
      - rabbitmq
  